[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
